routes/web.php
<?php

use App\Http\Controllers\BencanaController;
use App\Http\Controllers\BanjirController;
use App\Http\Controllers\KarhutlaBulanController;
use App\Http\Controllers\BanjirBulanController;
use App\Http\Controllers\PohonController;
use App\Http\Controllers\KarhutlaController;
use Illuminate\Support\Facades\Route;

Route::resource('bencana', BencanaController::class);
Route::resource('bencana/karhutla', KarhutlaController::class);
Route::resource('bencana/karhutla/data/k', KarhutlaBulanController::class);
Route::resource('bencana/banjir', BanjirController::class);
Route::resource('bencana/banjir/data/b', BanjirBulanController::class);
Route::resource('bencana/pohon', PohonController::class);
Route::get('/', [BencanaController::class, 'dashboard'])->name('dashboard');
Route::post('getKelurahan', [KarhutlaController::class, 'json_getKelurahan'])->name('getkelurahan');
Route::get('download/karhutla/bulan/image/{id}/{bulan}', [KarhutlaBulanController::class, 'makeimage'])->name('download.karhutla.bulan.image');
Route::get('download/karhutla/tahun/image/{id}', [KarhutlaController::class, 'makeimage'])->name('download.karhutla.tahun.image');
Route::get('bencana/karhutla/{id}/{bulan}', [KarhutlaBulanController::class, 'edit'])->name('karhutla.bulan.edit');

Route::get('download/banjir/bulan/image/{id}/{bulan}', [BanjirBulanController::class, 'makeimage'])->name('download.banjir.bulan.image');
Route::get('download/banjir/tahun/image/{id}', [BanjirController::class, 'makeimage'])->name('download.banjir.tahun.image');
Route::get('bencana/banjir/{id}/{bulan}', [BanjirBulanController::class, 'edit'])->name('banjir.bulan.edit');

app/Models/Banjir.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banjir extends Model
{
    use HasFactory;
    protected $table = 'banjir';
    protected $fillable = [
        'bencana_id',
        'bulan',
    ];
}

app/Http/Controllers/BanjirController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Bencana;
use App\Models\BanjirBulan;
use App\Models\Banjir;
use Image;
use File;

class BanjirController extends Controller
{
    public function index()
    {
        //
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $bencana_id = $request->bencana_id;
        $bulan = $request->bulan;

        foreach ($bencana_id as $key => $k) {
            $input['bencana_id'] = $k;
            $input['bulan'] = $bulan[$key];
            Banjir::create($input);
        }

        return back()
            ->with([
                'success' => 'Berhasil!!',
                'isi' => 'Bulan berhasil dibuat...',
            ]);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $bencana = Bencana::findOrFail($id);
        $data_bulan = BanjirBulan::where('bencana_id', $id)->orderBy('district_id', 'DESC')->get();
        $banjir_bulan = Banjir::where('bencana_id', $id)->get();
        $bulan = array('Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember');

        $januari = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Januari')->get();
        $februari = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Februari')->get();
        $maret = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Maret')->get();
        $april = BanjirBulan::where('bencana_id', $id)->where('bulan', 'April')->get();
        $mei = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Mei')->get();
        $juni = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Juni')->get();
        $juli = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Juli')->get();
        $agustus = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Agustus')->get();
        $september = BanjirBulan::where('bencana_id', $id)->where('bulan', 'September')->get();
        $oktober = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Oktober')->get();
        $november = BanjirBulan::where('bencana_id', $id)->where('bulan', 'November')->get();
        $desember = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Desember')->get();

        $kelurahan1 = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('kelurahan_terdampak');
        $kelurahan2 = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('kelurahan_terdampak');
        $kelurahan3 = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('kelurahan_terdampak');
        $kelurahan4 = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('kelurahan_terdampak');
        $kelurahan5 = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('kelurahan_terdampak');
        $kelurahan6 = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('kelurahan_terdampak');

        $penduduk1 = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('penduduk_terdampak');
        $penduduk2 = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('penduduk_terdampak');
        $penduduk3 = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('penduduk_terdampak');
        $penduduk4 = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('penduduk_terdampak');
        $penduduk5 = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('penduduk_terdampak');
        $penduduk6 = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('penduduk_terdampak');

        $rumah1 = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('rumah_terendam');
        $rumah2 = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('rumah_terendam');
        $rumah3 = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('rumah_terendam');
        $rumah4 = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('rumah_terendam');
        $rumah5 = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('rumah_terendam');
        $rumah6 = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('rumah_terendam');

        return view('page.bencana.banjir.index', compact('bencana', 'data_bulan', 'banjir_bulan', 'bulan', 'kelurahan1', 'kelurahan2', 'kelurahan3', 'kelurahan4', 'kelurahan5', 'kelurahan6', 'penduduk1', 'penduduk2', 'penduduk3', 'penduduk4', 'penduduk5', 'penduduk6', 'rumah1', 'rumah2', 'rumah3', 'rumah4', 'rumah5', 'rumah6', 'januari', 'februari', 'maret', 'april', 'mei', 'juni', 'juli', 'agustus', 'september', 'oktober', 'november', 'desember'));
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }

    public function makeimage($id)
    {
        $kelurahan_terdampak = BanjirBulan::where('bencana_id', $id)->sum('kelurahan_terdampak');
        $penduduk_terdampak = BanjirBulan::where('bencana_id', $id)->sum('penduduk_terdampak');
        $rumah_terendam = BanjirBulan::where('bencana_id', $id)->sum('rumah_terendam');
        $tahun = Bencana::where('id', $id)->first();
        $kolam_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('kelurahan_terdampak');
        $kolam_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('penduduk_terdampak');
        $kolam_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('rumah_terendam');
        $arsel_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('kelurahan_terdampak');
        $arsel_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('penduduk_terdampak');
        $arsel_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('rumah_terendam');
        $kumai_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('kelurahan_terdampak');
        $kumai_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('penduduk_terdampak');
        $kumai_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('rumah_terendam');
        $banteng_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('kelurahan_terdampak');
        $banteng_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('penduduk_terdampak');
        $banteng_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('rumah_terendam');
        $lada_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('kelurahan_terdampak');
        $lada_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('penduduk_terdampak');
        $lada_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('rumah_terendam');
        $aruta_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('kelurahan_terdampak');
        $aruta_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('penduduk_terdampak');
        $aruta_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('rumah_terendam');
        $img = Image::make(public_path('images/template/template_banjir.png'));

        #BULAN/TAHUN
        $waktu = 'Tahun ' . $tahun->tahun;
        $waktu_x = '142';
        $waktu_y = '101';
        $img->text(
            $waktu,
            $waktu_x,
            $waktu_y + 1,
            function ($font) {
                $font->file(public_path('font/Calibri-Bold.TTF'));
                $font->size(38);
                $font->color('#ffffff');
                $font->align('left');
                $font->valign('top');
            }
        );
        #BULAN/TAHUN

        #TOTAL DESA/KELURAHAN TERDAMPAK
        $kelurahan = $kelurahan_terdampak;
        $total_x = '115';
        $total_y = '250';
        if (strlen($kelurahan) == 1) {
            $total_xh = $total_x + 18;
        } elseif (strlen($kelurahan) == 2) {
            $total_xh = $total_x + 32;
        } elseif (strlen($kelurahan) == 3) {
            $total_xh = $total_x + 45;
        } elseif (strlen($kelurahan) == 4) {
            $total_xh = $total_x + 58;
        } elseif (strlen($kelurahan) == 5) {
            $total_xh = $total_x + 70;
        } else {
            $total_xh = $total_x + 70;
        }
        $img->text(
            $kelurahan,
            $total_x,
            $total_y + 2,
            function ($font) {
                $font->file(public_path('font/Calibri-Regular.ttf'));
                $font->size(25);
                $font->color('#f6ff00');
                $font->align('left');
                $font->valign('top');
            }
        );
        $img->text(
            'Desa / Kelurahan',
            $total_xh,
            $total_y,
            function ($font) {
                $font->file(public_path('font/Calibri-Regular.ttf'));
                $font->size(25);
                $font->color('#ffffff');
                $font->align('left');
                $font->valign('top');
            }
        );
        #TOTAL DESA/KELURAHAN TERDAMPAK
        #TOTAL PENDUDUK TERDAMPAK
        $penduduk = $penduduk_terdampak;
        $total_x = '115';
        $total_y_penduduk = '282';
        if (strlen($penduduk) == 1) {
            $total_x_penduduk = $total_x + 18;
        } elseif (strlen($penduduk) == 2) {
            $total_x_penduduk = $total_x + 32;
        } elseif (strlen($penduduk) == 3) {
            $total_x_penduduk = $total_x + 45;
        } elseif (strlen($penduduk) == 4) {
            $total_x_penduduk = $total_x + 58;
        } elseif (strlen($penduduk) == 5) {
            $total_x_penduduk = $total_x + 70;
        } else {
            $total_x_penduduk = $total_x + 70;
        }

resources/views/page/bencana/banjir/bulan/index.blade.php
@php
use Carbon\Carbon;
@endphp
@extends('master')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/sweetalert2/sweetalert2.min.css')}}">
@endsection

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Data Bencana {{$bencana->jenis}} {{$getbulan->bulan}} {{$bencana->tahun}}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <!-- <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li> -->
          <li class="breadcrumb-item"><a href="{{route('bencana.index')}}">Data Bencana</a></li>
          <li class="breadcrumb-item active">{{$bencana->jenis}} {{$getbulan->bulan}} {{$bencana->tahun}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <a href="{{route('banjir.edit',$bencana->id)}}" class="btn btn-sm btn-outline-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
            @if($ifkolam -> isEmpty() || $ifarsel -> isEmpty() || $ifkumai -> isEmpty() || $ifbanteng -> isEmpty() || $iflada -> isEmpty() || $ifaruta -> isEmpty())
            @else
            <a href="{{route('download.banjir.bulan.image',[$bencana->id,$getbulan->bulan])}}" class="btn btn-sm btn-primary float-sm-right"><i class="fa fa-download"></i> Download Infografis {{$getbulan->bulan}} {{$bencana->tahun}}</a>
            @endif
          </div>
          <div class="card-header">
            @if($ifkolam -> isEmpty())
            <button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#kotawaringin_lama"><i class="fa fa-plus"></i> Kotawaringin Lama</button>
            @else
            @foreach($ifkolam as $i)
            <button class="btn btn-sm btn-outline-success kolam" data-bulan="{{$i->bulan}}" data-id="{{$i->id}}" data-bencana_id="{{$bencana->id}}" data-district_id="1"><i class="fa fa-edit"></i> Kotawaringin Lama</button>
            @endforeach
            @endif
            @if($ifarsel -> isEmpty())
            <button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#arut_selatan"><i class="fa fa-plus"></i> Arut Selatan</button>
            @else
            @foreach($ifarsel as $i)
            <button class="btn btn-sm btn-outline-success arsel" data-bulan="{{$i->bulan}}" data-id="{{$i->id}}" data-bencana_id="{{$bencana->id}}" data-district_id="2"><i class="fa fa-edit"></i> Arut Selatan</button>
            @endforeach
            @endif
            @if($ifkumai -> isEmpty())
            <button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#kumai"><i class="fa fa-plus"></i> Kumai</button>
            @else
            @foreach($ifkumai as $i)
            <button class="btn btn-sm btn-outline-success kumai" data-bulan="{{$i->bulan}}" data-id="{{$i->id}}" data-bencana_id="{{$bencana->id}}" data-district_id="3"><i class="fa fa-edit"></i> Kumai</button>
            @endforeach
            @endif
            @if($ifbanteng -> isEmpty())
            <button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#pangkalan_banteng"><i class="fa fa-plus"></i> Pangkalan Banteng</button>
            @else
            @foreach($ifbanteng as $i)
            <button class="btn btn-sm btn-outline-success banteng" data-bulan="{{$i->bulan}}" data-id="{{$i->id}}" data-bencana_id="{{$bencana->id}}" data-district_id="4"><i class="fa fa-edit"></i> Pangkalan Banteng</button>
            @endforeach
            @endif
            @if($iflada -> isEmpty())
            <button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#pangkalan_lada"><i class="fa fa-plus"></i> Pangkalan Lada</button>
            @else
            @foreach($iflada as $i)
            <button class="btn btn-sm btn-outline-success lada" data-bulan="{{$i->bulan}}" data-id="{{$i->id}}" data-bencana_id="{{$bencana->id}}" data-district_id="5"><i class="fa fa-edit"></i> Pangkalan Lada</button>
            @endforeach
            @endif
            @if($ifaruta -> isEmpty())
            <button class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#arut_utara"><i class="fa fa-plus"></i> Arut Utara</button>
            @else
            @foreach($ifaruta as $i)
            <button class="btn btn-sm btn-outline-success aruta" data-bulan="{{$i->bulan}}" data-id="{{$i->id}}" data-bencana_id="{{$bencana->id}}" data-district_id="6"><i class="fa fa-edit"></i> Arut Utara</button>
            @endforeach
            @endif
          </div>
          <div class="card-body">
            <table class="table table-bordered" id="tablze">
              <thead>
                <tr class="text-center">
                  <th>Kecamatan</th>
                  <th>Desa/Kelurahan Terdampak</th>
                  <th>Penduduk Terdampak</th>
                  <th>Rumah Terendam</th>
                </tr>
                <tr class="text-center">
                </tr>
              </thead>
              <tbody>
                @foreach($databulan as $k)
                <tr>
                  <td>{{$k->district->nama}}</td>
                  <td class="text-center">{{$k->kelurahan_terdampak}}</td>
                  <td class="text-center">{{$k->penduduk_terdampak}}</td>
                  <td class="text-center">{{$k->rumah_terendam}}</td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
</section>
@endsection

@section('modal')
@include('page.bencana.banjir.bulan.modal_edit')
@endsection



@section('script')
<!-- DataTables -->
<script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('plugins/select2/js/select2.full.min.js')}}"></script>
<script src="{{asset('plugins/sweetalert2/sweetalert2.min.js')}}"></script>
<script src="{{asset('plugins/jquery-validation/jquery.validate.min.js')}}"></script>

@include('page.bencana.banjir.bulan.js')
<script>
  //script konfirmasi hapus
  $.ajaxSetup({
    headers: {
      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
  })
  $('.hapus').click(function(e) {
    // id = e.target.dataset.id;
    e.preventDefault();
    var delete_id = $(this).attr('data-id');
    Swal.fire({
      title: 'Apakah anda yakin?',
      text: "Anda tidak dapat mengembalikan data yang telah dihapus!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Ya, Hapus Sekarang!',
      cancelButtonText: 'Batalkan'
    }).then(function(result) {
      if (result.value) {
        var data = {
          "_token": $('input[name=_token]').val(),
          "id": delete_id
        }
        $.ajax({
          type: "DELETE",
          url: '/bencana/' + delete_id,
          data: data,
          success: function(data) {
            Swal.fire(
                'Berhasil!',
                'Data Bencana berhasil dihapus...',
                'success'
              )
              .then((result) => {
                location.reload();
              })
            // console.log(result)
          }
        })
      } else {
        // console.log(`dialog was dismissed by ${result.dismiss}`)
        Swal.fire(
          'Gagal!',
          'Hapus data telah dibatalkan...',
          'error'
        )
      }
    })
  })
</script>

@if(session("success"))
<script>
  const Toast = Swal.mixin({
    toast: true,
    position: 'top',
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true,
    didOpen: (toast) => {
      toast.addEventListener('mouseenter', Swal.stopTimer)
      toast.addEventListener('mouseleave', Swal.resumeTimer)
    }
  })

  Toast.fire({
    icon: 'success',
    title: '{{session("isi")}}'
  })
</script>
@endif

<script>
  $(function() {
    $.ajaxSetup({
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    });

    $('#kecamatan').on('change', function() {
      $.ajax({
        url: '{{ route("getkelurahan") }}',
        method: 'POST',
        data: {
          id: $(this).val()
        },
        success: function(response) {
          $('#kelurahan').empty();
          $.each(response, function(id, nama) {
            $('#kelurahan').append(new Option(nama, id))
          })
          console.log(response)
        }
      })
    });
  });
</script>
@include('page.bencana.banjir.bulan.validation_js')
@endsection