routes/web.php
<?php

use App\Http\Controllers\BencanaController;
use App\Http\Controllers\BanjirController;
use App\Http\Controllers\KarhutlaBulanController;
use App\Http\Controllers\BanjirBulanController;
use App\Http\Controllers\PohonController;
use App\Http\Controllers\KarhutlaController;
use Illuminate\Support\Facades\Route;

Route::resource('bencana', BencanaController::class);
Route::resource('bencana/karhutla', KarhutlaController::class);
Route::resource('bencana/karhutla/data/k', KarhutlaBulanController::class);
Route::resource('bencana/banjir', BanjirController::class);
Route::resource('bencana/banjir/data/b', BanjirBulanController::class);
Route::resource('bencana/pohon', PohonController::class);
Route::get('/', [BencanaController::class, 'dashboard'])->name('dashboard');
Route::post('getKelurahan', [KarhutlaController::class, 'json_getKelurahan'])->name('getkelurahan');
Route::get('download/karhutla/bulan/image/{id}/{bulan}', [KarhutlaBulanController::class, 'makeimage'])->name('download.karhutla.bulan.image');
Route::get('download/karhutla/tahun/image/{id}', [KarhutlaController::class, 'makeimage'])->name('download.karhutla.tahun.image');
Route::get('bencana/karhutla/{id}/{bulan}', [KarhutlaBulanController::class, 'edit'])->name('karhutla.bulan.edit');

Route::get('download/banjir/bulan/image/{id}/{bulan}', [BanjirBulanController::class, 'makeimage'])->name('download.banjir.bulan.image');
Route::get('download/banjir/tahun/image/{id}', [BanjirController::class, 'makeimage'])->name('download.banjir.tahun.image');
Route::get('bencana/banjir/{id}/{bulan}', [BanjirBulanController::class, 'edit'])->name('banjir.bulan.edit');

app/Models/Banjir.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banjir extends Model
{
    use HasFactory;
    protected $table = 'banjir';
    protected $fillable = [
        'bencana_id',
        'bulan',
    ];
}

app/Models/Bencana.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bencana extends Model
{
    use HasFactory;
    protected $table = 'bencana';
    protected $fillable = [
        'jenis',
        'tahun',
    ];
}

app/Http/Controllers/BanjirController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Bencana;
use App\Models\BanjirBulan;
use App\Models\Banjir;
use Image;
use File;

class BanjirController extends Controller
{
    public function index()
    {
        //
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $bencana_id = $request->bencana_id;
        $bulan = $request->bulan;

        foreach ($bencana_id as $key => $k) {
            $input['bencana_id'] = $k;
            $input['bulan'] = $bulan[$key];
            Banjir::create($input);
        }

        return back()
            ->with([
                'success' => 'Berhasil!!',
                'isi' => 'Bulan berhasil dibuat...',
            ]);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $bencana = Bencana::findOrFail($id);
        $data_bulan = BanjirBulan::where('bencana_id', $id)->orderBy('district_id', 'DESC')->get();
        $banjir_bulan = Banjir::where('bencana_id', $id)->get();
        $bulan = array('Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember');

        $januari = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Januari')->get();
        $februari = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Februari')->get();
        $maret = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Maret')->get();
        $april = BanjirBulan::where('bencana_id', $id)->where('bulan', 'April')->get();
        $mei = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Mei')->get();
        $juni = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Juni')->get();
        $juli = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Juli')->get();
        $agustus = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Agustus')->get();
        $september = BanjirBulan::where('bencana_id', $id)->where('bulan', 'September')->get();
        $oktober = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Oktober')->get();
        $november = BanjirBulan::where('bencana_id', $id)->where('bulan', 'November')->get();
        $desember = BanjirBulan::where('bencana_id', $id)->where('bulan', 'Desember')->get();

        $kelurahan1 = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('kelurahan_terdampak');
        $kelurahan2 = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('kelurahan_terdampak');
        $kelurahan3 = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('kelurahan_terdampak');
        $kelurahan4 = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('kelurahan_terdampak');
        $kelurahan5 = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('kelurahan_terdampak');
        $kelurahan6 = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('kelurahan_terdampak');

        $penduduk1 = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('penduduk_terdampak');
        $penduduk2 = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('penduduk_terdampak');
        $penduduk3 = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('penduduk_terdampak');
        $penduduk4 = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('penduduk_terdampak');
        $penduduk5 = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('penduduk_terdampak');
        $penduduk6 = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('penduduk_terdampak');

        $rumah1 = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('rumah_terendam');
        $rumah2 = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('rumah_terendam');
        $rumah3 = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('rumah_terendam');
        $rumah4 = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('rumah_terendam');
        $rumah5 = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('rumah_terendam');
        $rumah6 = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('rumah_terendam');

        return view('page.bencana.banjir.index', compact('bencana', 'data_bulan', 'banjir_bulan', 'bulan', 'kelurahan1', 'kelurahan2', 'kelurahan3', 'kelurahan4', 'kelurahan5', 'kelurahan6', 'penduduk1', 'penduduk2', 'penduduk3', 'penduduk4', 'penduduk5', 'penduduk6', 'rumah1', 'rumah2', 'rumah3', 'rumah4', 'rumah5', 'rumah6', 'januari', 'februari', 'maret', 'april', 'mei', 'juni', 'juli', 'agustus', 'september', 'oktober', 'november', 'desember'));
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($id)
    {
        //
    }

    public function makeimage($id)
    {
        $kelurahan_terdampak = BanjirBulan::where('bencana_id', $id)->sum('kelurahan_terdampak');
        $penduduk_terdampak = BanjirBulan::where('bencana_id', $id)->sum('penduduk_terdampak');
        $rumah_terendam = BanjirBulan::where('bencana_id', $id)->sum('rumah_terendam');
        $tahun = Bencana::where('id', $id)->first();
        $kolam_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('kelurahan_terdampak');
        $kolam_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('penduduk_terdampak');
        $kolam_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 1)->sum('rumah_terendam');
        $arsel_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('kelurahan_terdampak');
        $arsel_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('penduduk_terdampak');
        $arsel_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 2)->sum('rumah_terendam');
        $kumai_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('kelurahan_terdampak');
        $kumai_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('penduduk_terdampak');
        $kumai_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 3)->sum('rumah_terendam');
        $banteng_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('kelurahan_terdampak');
        $banteng_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('penduduk_terdampak');
        $banteng_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 4)->sum('rumah_terendam');
        $lada_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('kelurahan_terdampak');
        $lada_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('penduduk_terdampak');
        $lada_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 5)->sum('rumah_terendam');
        $aruta_kelurahan = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('kelurahan_terdampak');
        $aruta_penduduk = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('penduduk_terdampak');
        $aruta_rumah = BanjirBulan::where('bencana_id', $id)->where('district_id', 6)->sum('rumah_terendam');
        $img = Image::make(public_path('images/template/template_banjir.png'));

        #BULAN/TAHUN
        $waktu = 'Tahun ' . $tahun->tahun;
        $waktu_x = '142';
        $waktu_y = '101';
        $img->text(
            $waktu,
            $waktu_x,
            $waktu_y + 1,
            function ($font) {
                $font->file(public_path('font/Calibri-Bold.TTF'));
                $font->size(38);
                $font->color('#ffffff');
                $font->align('left');
                $font->valign('top');
            }
        );
        #BULAN/TAHUN

        #TOTAL DESA/KELURAHAN TERDAMPAK
        $kelurahan = $kelurahan_terdampak;
        $total_x = '115';
        $total_y = '250';
        if (strlen($kelurahan) == 1) {
            $total_xh = $total_x + 18;
        } elseif (strlen($kelurahan) == 2) {
            $total_xh = $total_x + 32;
        } elseif (strlen($kelurahan) == 3) {
            $total_xh = $total_x + 45;
        } elseif (strlen($kelurahan) == 4) {
            $total_xh = $total_x + 58;
        } elseif (strlen($kelurahan) == 5) {
            $total_xh = $total_x + 70;
        } else {
            $total_xh = $total_x + 70;
        }
        $img->text(
            $kelurahan,
            $total_x,
            $total_y + 2,
            function ($font) {
                $font->file(public_path('font/Calibri-Regular.ttf'));
                $font->size(25);
                $font->color('#f6ff00');
                $font->align('left');
                $font->valign('top');
            }
        );
        $img->text(
            'Desa / Kelurahan',
            $total_xh,
            $total_y,
            function ($font) {
                $font->file(public_path('font/Calibri-Regular.ttf'));
                $font->size(25);
                $font->color('#ffffff');
                $font->align('left');
                $font->valign('top');
            }
        );
        #TOTAL DESA/KELURAHAN TERDAMPAK
        #TOTAL PENDUDUK TERDAMPAK
        $penduduk = $penduduk_terdampak;
        $total_x = '115';
        $total_y_penduduk = '282';
        if (strlen($penduduk) == 1) {
            $total_x_penduduk = $total_x + 18;
        } elseif (strlen($penduduk) == 2) {
            $total_x_penduduk = $total_x + 32;
        } elseif (strlen($penduduk) == 3) {
            $total_x_penduduk = $total_x + 45;
        } elseif (strlen($penduduk) == 4) {
            $total_x_penduduk = $total_x + 58;
        } elseif (strlen($penduduk) == 5) {
            $total_x_penduduk = $total_x + 70;
        } else {
            $total_x_penduduk = $total_x + 70;
        }

app/Http/Controllers/BencanaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Bencana;
use Illuminate\Support\Facades\Redirect;

class BencanaController extends Controller
{
    public function dashboard()
    {
        // return view('page.dashboard');
        return redirect()->route('bencana.index');
    }

    public function index()
    {
        $bencana = Bencana::orderBy('id', 'DESC')->get();
        $jenis = array('Karhutla', 'Banjir');
        return view('page.bencana.index', compact('bencana', 'jenis'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $rules = [
            'jenis' => 'required',
            'tahun' => 'required',
        ];
        $customMessages = [
            'required' => ':Attribute tidak boleh kosong!',
        ];
        $this->validate($request, $rules, $customMessages);

        $datas = new Bencana;
        $datas->jenis = $request->jenis;
        $datas->tahun = $request->tahun;
        $datas->save();

        return back()
            ->with([
                'success' => 'Berhasil!!',
                'isi' => 'Data Bencana telah ditambahkan...',
            ]);
    }

    public function json_edit(request $request)
    {
        $data = Bencana::where('id', $request->id)->first();
        return response()->json($data);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
    }

    public function update(Request $request, $id)
    {
        $datas = Bencana::findOrFail($id);;
        $datas->jenis = $request->jenis;
        $datas->tahun = $request->tahun;
        $datas->save();

        return back()
            ->with([
                'success' => 'Berhasil!!',
                'isi' => 'Data Bencana telah diperbaharui...',
            ]);
    }

    public function destroy($id)
    {
        $data = Bencana::findOrFail($id);
        // $data = Bencana::find($request->id)->delete();
        $data->delete();
        // Bencana::where('id', $id)->delete();

        return response()->json([
            'status' => 'test'
        ]);

        // return back()
        //     ->with('success', 'Berhasil!')
        //     ->with('isi', 'Data Bencana telah dihapus...');
    }
}

resources/views/page/bencana/banjir/index.blade.php
@extends('master')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('plugins/sweetalert2/sweetalert2.min.css')}}">
@endsection

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Data Bencana {{$bencana->jenis}} Tahun {{$bencana->tahun}}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <!-- <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li> -->
          <li class="breadcrumb-item"><a href="{{route('bencana.index')}}">Data Bencana</a></li>
          <li class="breadcrumb-item active">{{$bencana->jenis}} {{$bencana->tahun}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <a href="{{route('bencana.index')}}" class="btn btn-sm btn-outline-primary"><i class="fa fa-arrow-left"></i> Kembali</a>
            @if($data_bulan -> isEmpty())
            @else
            <a href="{{route('download.banjir.tahun.image',$bencana->id)}}" class="btn btn-sm btn-primary float-sm-right"><i class="fa fa-download"></i> Download Infografis Tahun {{$bencana->tahun}}</a>
            @endif
          </div>
          <div class="card-header">
            @if($banjir_bulan->isEmpty())
            <form action="{{route('banjir.store')}}" method="post">
              @csrf
              @foreach($bulan as $b)
              <input name="bencana_id[]" value="{{$bencana->id}}" type="hidden">
              <input name="bulan[]" value="{{$b}}" type="hidden">
              @endforeach
              <button type="submit" class=" btn btn-sm btn-outline-primary">Buat Bulan</button>
            </form>
            @else

            @if($januari->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Januari'])}}" class="btn btn-sm btn-outline-primary">Januari</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Januari'])}}" class="btn btn-sm btn-outline-success">Januari</a>
            @endif
            @if($februari->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Februari'])}}" class="btn btn-sm btn-outline-primary">Februari</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Februari'])}}" class="btn btn-sm btn-outline-success">Februari</a>
            @endif
            @if($maret->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Maret'])}}" class="btn btn-sm btn-outline-primary">Maret</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Maret'])}}" class="btn btn-sm btn-outline-success">Maret</a>
            @endif
            @if($april->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'April'])}}" class="btn btn-sm btn-outline-primary">April</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'April'])}}" class="btn btn-sm btn-outline-success">April</a>
            @endif
            @if($mei->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Mei'])}}" class="btn btn-sm btn-outline-primary">Mei</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Mei'])}}" class="btn btn-sm btn-outline-success">Mei</a>
            @endif
            @if($juni->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Juni'])}}" class="btn btn-sm btn-outline-primary">Juni</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Juni'])}}" class="btn btn-sm btn-outline-success">Juni</a>
            @endif
            @if($juli->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Juli'])}}" class="btn btn-sm btn-outline-primary">Juli</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Juli'])}}" class="btn btn-sm btn-outline-success">Juli</a>
            @endif
            @if($agustus->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Agustus'])}}" class="btn btn-sm btn-outline-primary">Agustus</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Agustus'])}}" class="btn btn-sm btn-outline-success">Agustus</a>
            @endif
            @if($september->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'September'])}}" class="btn btn-sm btn-outline-primary">September</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'September'])}}" class="btn btn-sm btn-outline-success">September</a>
            @endif
            @if($oktober->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Oktober'])}}" class="btn btn-sm btn-outline-primary">Oktober</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Oktober'])}}" class="btn btn-sm btn-outline-success">Oktober</a>
            @endif
            @if($november->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'November'])}}" class="btn btn-sm btn-outline-primary">November</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'November'])}}" class="btn btn-sm btn-outline-success">November</a>
            @endif
            @if($desember->isEmpty())
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Desember'])}}" class="btn btn-sm btn-outline-primary">Desember</a>
            @else
            <a href="{{route('banjir.bulan.edit',[$bencana->id,'Desember'])}}" class="btn btn-sm btn-outline-success">Desember</a>
            @endif

            @endif
          </div>

          <div class="card-body">
            <table class="table table-bordered" id="tablze">
              <thead>
                <tr class="text-center">
                  <th>Kecamatan</th>
                  <th>Desa/Kelurahan Terdampak</th>
                  <th>Penduduk Terdampak</th>
                  <th>Rumah Terendam</th>
                </tr>
                <tr class="text-center">
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Kotawaringin Lama</td>
                  <td class="text-center">{{$kelurahan1}}</td>
                  <td class="text-center">{{$penduduk1}}</td>
                  <td class="text-center">{{$rumah1}}</td>
                </tr>
                <tr>
                  <td>Arut Selatan</td>
                  <td class="text-center">{{$kelurahan2}}</td>
                  <td class="text-center">{{$penduduk2}}</td>
                  <td class="text-center">{{$rumah2}}</td>
                </tr>
                <tr>
                  <td>Kumai</td>
                  <td class="text-center">{{$kelurahan3}}</td>
                  <td class="text-center">{{$penduduk3}}</td>
                  <td class="text-center">{{$rumah3}}</td>
                </tr>
                <tr>
                  <td>Pangkalan Banteng</td>
                  <td class="text-center">{{$kelurahan4}}</td>
                  <td class="text-center">{{$penduduk4}}</td>
                  <td class="text-center">{{$rumah4}}</td>
                </tr>
                <tr>
                  <td>Pangkalan Lada</td>
                  <td class="text-center">{{$kelurahan5}}</td>
                  <td class="text-center">{{$penduduk5}}</td>
                  <td class="text-center">{{$rumah5}}</td>
                </tr>
                <tr>
                  <td>Arut Utara</td>
                  <td class="text-center">{{$kelurahan6}}</td>
                  <td class="text-center">{{$penduduk6}}</td>
                  <td class="text-center">{{$rumah6}}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
</section>
@endsection

@section('script')
<!-- DataTables -->
<script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{asset('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{asset('plugins/sweetalert2/sweetalert2.min.js')}}"></script>
<script src="{{asset('plugins/jquery-validation/jquery.validate.min.js')}}"></script>
@if(session("success"))
<script>
  const Toast = Swal.mixin({
    toast: true,
    position: 'top',
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true,
    didOpen: (toast) => {
      toast.addEventListener('mouseenter', Swal.stopTimer)
      toast.addEventListener('mouseleave', Swal.resumeTimer)
    }
  })

  Toast.fire({
    icon: 'success',
    title: '{{session("isi")}}'
  })
</script>
@endif

@endsection